### ISSUE TITLE
Instructions lacking... Now that I ran build.. now what

### ISSUE THREAD

**Issue by parsonsalan1** [OGSegu/Twitch-View-Bot#10]

**Comment by OGSegu** [comment]
After you built a project by Gradle, there will be a file in the path below:
![image](https://user-images.githubusercontent.com/51200522/103351468-6987ac80-4ab4-11eb-8e21-4a447ee74034.png)

**Comment by parsonsalan1** [comment]
Right, thanks for the response. But is this accessed via port 80? configuration?

**Comment by parsonsalan1** [comment]
![image](https://user-images.githubusercontent.com/35387431/103378589-cb461780-4ab0-11eb-8109-a529ae994ca6.png)

**Comment by OGSegu** [comment]
Did you solve it?

**Comment by parsonsalan1** [comment]
no, I moved on. no big deal, thanks.

**Comment by SantiParris8** [comment]
Im having the same issue, 

`java.lang.ClassNotFoundException: com.sun.glass.ui.win.WinPlatformFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

I have tried manually installing the openjfx library but nothing changed
